wafV2Config:
  - stackName: "TestStack1"
    requestThreshold: 500
    albArn: "arn:aws:elasticloadbalancing:us-east-2:205631354229:loadbalancer/app/newloadbalancer/8608a48e005cb977"
    region: "us-east-1"
    rateLimitRuleAction: "Count"
    activateHttpFloodProtectionParam: "yes"
